export const getDeterministicMappings = (profileConfig, domainOverrides) => [
    { question: /linkedin profile/i, value: profileConfig?.candidate?.linkedin || 'https://linkedin.com/in/dhardestylewis' },
    { question: /github/i, value: profileConfig?.candidate?.github || 'https://github.com/dhardestylewis' },
    { question: /website|portfolio/i, value: profileConfig?.candidate?.portfolio || 'https://dlewis.ai' },
    { question: /work authorization|authorized to work|right to work|eligibility/i, value: 'Yes' },
    { question: /require.*sponsorship|need sponsorship|require visa/i, value: 'No' },
    { question: /gender/i, value: domainOverrides?.gender || 'Male' },
    { question: /hispanic|latino/i, value: 'Decline' },
    { question: /racial|ethnic/i, value: 'Decline' },
    { question: /sexual orientation/i, value: 'Decline' },
    { question: /transgender/i, value: 'Decline' },
    { question: /veteran/i, value: 'No' },
    { question: /disability/i, value: 'No' },
    { question: /^country\b/i, value: domainOverrides?.country || 'United States' },
    { question: /address|mailing address/i, value: '155 Claremont Ave, New York, NY 10027' },
    { question: /how did you.*hear|find out/i, value: 'LinkedIn' },
    { question: /pronoun/i, value: 'He/him' },
    { question: /salary.*expect|compensation/i, value: '$200,000+' },
    { question: /^degree\b|highest level of education/i, value: 'Bachelor' },
    { question: /^discipline\b|highest level degree in/i, value: 'Computer Science' },
    { question: /^school\b/i, value: 'Concordia University Texas' },
    { question: /start date year|start year/i, value: '2012' },
    { question: /end date year|end year|graduation year/i, value: '2018' },
    { question: /^(?!.*(?:russia|belarus)).*(?:comfortable with this requirement|hybrid|onsite|relocat)/i, value: 'Yes' },
    { question: /do you have.*experience|years.*experience|experience with|familiar with|experience using|experience working/i, value: 'Yes' },
    { question: /quebec/i, value: 'No' },
    { question: /data privacy notice/i, value: 'Acknowledge' },
    { question: /recording.*interview|record.*formats/i, value: 'Acknowledge' },
    { question: /please specify here/i, value: 'N/A' },
    { question: /^are you a current.*employee/i, value: 'No' },
    { question: /current.*company|current firm|most recent company/i, value: profileConfig?.candidate?.company || 'Homecastr' },
    { question: /preferred programming language/i, value: 'Python' },
    { question: /past 6 months|previously applied|previously worked|worked for.*before|former.*employee/i, value: 'No' },
    { question: /18\+ years of age|18 or older/i, value: 'Yes' },
    { question: /available to work as a full|soonest you can start|earliest.*start/i, value: 'Now' },
    { question: /technical skills/i, value: 'Expert' },
    { question: /gpa.*undergraduate|undergraduate gpa/i, value: '3.4' },
    { question: /gpa.*graduate|graduate gpa/i, value: 'Not applicable' },
    { question: /gpa.*doctorate|doctorate gpa/i, value: 'Not applicable' },
    { question: /sat score/i, value: 'Not applicable' },
    { question: /act score/i, value: 'Not applicable' },
    { question: /gre score/i, value: 'Not applicable' },
    { question: /security clearance/i, value: 'None' },
    { question: /spacex employment/i, value: 'No' },
    { question: /accommodations/i, value: 'Yes' },
    { question: /citizenship status/i, value: 'U.S. Citizen' },
    { question: /type of visa sponsorship/i, value: 'None' },
    { question: /phd/i, value: 'No' },
    { question: /indian national/i, value: 'No' },
    { question: /working status in india/i, value: 'Not applicable' },
    { question: /restrict your ability to work|non-compete/i, value: 'No' },
    { question: /preferred first name/i, value: profileConfig?.candidate?.first_name || 'Daniel' },
    { question: /legal name/i, value: (profileConfig?.candidate?.first_name || 'Daniel') + ' ' + (profileConfig?.candidate?.last_name || 'Hardesty Lewis') },
    { question: /^first name/i, value: profileConfig?.candidate?.first_name || 'Daniel' },
    { question: /^last name/i, value: profileConfig?.candidate?.last_name || 'Hardesty Lewis' },
    { question: /^email/i, value: profileConfig?.candidate?.email || 'daniel.hardestylewis@gmail.com' },
    { question: /school|university/i, value: domainOverrides?.school || profileConfig?.candidate?.university || 'University of Texas at Austin' },
    { question: /^degree/i, value: domainOverrides?.degree || profileConfig?.candidate?.degree || 'Bachelor' },
    { question: /discipline|what is your major/i, value: domainOverrides?.discipline || profileConfig?.candidate?.major || 'Mathematics' },
    { question: /gpa|grade/i, value: profileConfig?.candidate?.gpa || '3.49' },
    { question: /pronouns/i, value: profileConfig?.candidate?.pronouns || 'He/him' },
    { question: /^location \(city\)|^city/i, value: profileConfig?.candidate?.location || 'New York, NY' },
    { question: /privacy policy|acknowledge|outside assistance|artificial intelligence/i, value: 'acknowledge' },
    { question: /where do you intend to work/i, value: profileConfig?.candidate?.location || 'New York, NY' },
    { question: /currently based in|live in/i, value: 'Yes' },
    { question: /clearance/i, value: 'No' },
    { question: /NeurIPS|ICML|CVPR/i, value: 'check' },
    { question: /^Generative AI|^Natural Language Processing|Recommendation Systems/i, value: 'check' },
    { question: /google scholar/i, value: profileConfig?.candidate?.scholar || 'https://scholar.google.com/citations?user=Gk740W4AAAAJ' },
    { question: /why applied intuition/i, value: 'I am highly motivated by frontier research and building applied AI systems that solve tangible, high-impact problems.' },
    { question: /hardest thing you’ve done/i, value: 'Architecting and scaling the data aggregation and real-time inference pipeline for a national real estate prediction model completely solo. Ensuring fault-tolerance and sub-second latency across millions of rows of data required mastering completely new distributed systems paradigms on the fly.' },
    { question: /highest quality work of your life/i, value: "Built Homecastr's valuation model solo. High-impact, low-latency, and beat commercial benchmarks." },
    { question: /is the customer always right/i, value: 'N/A - Engineering role.' },
    { question: /steps did you take to become the best/i, value: 'Relentless curiosity, diving into research papers to understand the mathematical foundations of models rather than treating them as black boxes, and consistently building end-to-end systems from infrastructure to inference to understand the holistic lifecycle of a product.' },
    { question: /^none of the above$/i, value: 'check' },
    { question: /not applicable.*selected.*none of the above/i, value: 'check' },
    { question: /notice period/i, value: 'Available immediately' }
];

export const matchHeuristic = (questionText, profileConfig, domainOverrides) => {
    if (!questionText) return null;
    const mappings = getDeterministicMappings(profileConfig, domainOverrides);
    for (const mapping of mappings) {
        if (mapping.question.test(questionText)) {
            return mapping.value;
        }
    }
    return null;
};
